trigger:
  branches:
    include:
      - refs/heads/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  hugoVersion: '0.64.0'

steps:
- checkout: self
  submodules: true

- script: |
    wget https://github.com/gohugoio/hugo/releases/download/v$(hugoVersion)/hugo_$(hugoVersion)_Linux-64bit.deb -O hugo.deb
    sudo dpkg -i hugo.deb
  displayName: Install Hugo

- script: hugo
  displayName: Generate Site

- script: hugo deploy --maxDeletes -1 --dryRun
  condition: succeeded()
  displayName: Dry Run Publish

- script: hugo deploy --maxDeletes -1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Publish