baseURL = "https://kotatsu.club"
disablePathToLower = true
languageCode = "en-us"
title = "Kotatsu Club"
theme = "hugo-theme-kotatsu"

disqusShortname="kotatsuclub"
googleAnalytics = "UA-77326078-1"
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[permalinks]
post = "/:filename"

### Deployment
[[deployment.targets]]
name = "Azure Blob Storage"
url = "azblob://$web"

### Theme settings
[taxonomies]
tag = "tags"
author = "author"

[params.social]
github = "https://github.com/kotatsuclub/blog"
twitter = "https://twitter.com/thekotatsuclub"

[params.rss]
rel = "/rss"