baseURL = "https://kotatsu.club"
disablePathToLower = true
languageCode = "en-us"
title = "Kotatsu Club"
theme = "notepadium"

### Theme settings

enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[[params.nav.custom]]
title = "RSS"
url = "/post/index.xml"