baseURL = "https://kotatsu.club"
disablePathToLower = true
languageCode = "en-us"
title = "Kotatsu Club"
theme = "notepadium"

disqusShortname="kotatsuclub"

### Theme settings

enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[[params.nav.custom]]
title = "RSS"
url = "/post/index.xml"

[params.comments]
enable = true

### Deployment

[[deployment.targets]]
name = "Azure Blob Storage"
url = "azblob://$web"