[build]
publish = "public"
command = "hugo --gc --minify"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.production.environment]
HUGO_VERSION = "0.82.0"

[context.deploy-preview.environment]
HUGO_VERSION = "0.82.0"

[context.branch-deploy.environment]
HUGO_VERSION = "0.82.0"

[[redirects]]
  from = "/rss"
  to = "/index.xml"
  status = 200